### ISSUE TITLE
Request Page and Parse HTML

### ISSUE THREAD

**Issue by Abhi10699** [Abhi10699/anime-db#1]
## Tasks 
- [ ] Send GET request to zoro.to and fetch HTML
- [ ] Parse HTML and create a list of titles with their corresponding watch link
- [ ] Insert anime in an sqlite database 

## Metadata
- Album Art
- Media Link
- Episodes [ description, length and link ]
- Category
- Likes and dislikes
- Release Date 
- Total Seasons
- Characters [IRL and In Series]
- Current Status [ More seasons coming or ended ]
- Genre
- Producers

**Comment by Abhi10699** [comment]
![image](https://user-images.githubusercontent.com/16337462/166506156-c5615b4d-1b00-4fb8-af15-16e09b11f97f.png)

**Schema Design**
